title: Your awesome title
author: Amol Bhide
theme: minima
email: abhide2@ebnet.org
description: >
  This is a blog description

# social links
twitter_username: N/A
github_username:  AB-Robotics

show_excerpts: true 
